include:
  - board: nice_nano_v2
    shield: stryke
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=n
  
  - board: nice_nano_v2
    shield: settings_reset
    cmake-args: -DCONFIG_ZMK_STUDIO=n  # Explicitly disable

modules:
  - name: custom_widgets
    path: widgets
    board: nice_nano_v2